var GP={CONFIG:{ValiErrorStyle:{suc:"t-suc",err:"t-err"}}};
GP.Message=function(){var d,e={suc:"i-suc1",load:"i-loading",err:"i-err1",war:"i-err1"},g,b=function(b,a){d||(d=$(String.format('<div class="pop-msg"><i class="icon"></i><span rel="con">%1</span></div>',b)),$(document.body).append(d),$(window).bind("resize",function(){var a=$(window).scrollTop()+(document.documentElement.clientHeight-d.height())/2.5;d.css({top:a+"px",left:($(document).width()-d.width())/2+"px"})}));var c=$(window).scrollTop()+(document.documentElement.clientHeight-d.height())/2.5;
d.css({top:c+"px",left:($(document).width()-d.width())/2+"px"});d.find("[rel='con']").html(b);var c=d.find(".icon"),f;for(f in e)c.removeClass(e[f]);c.addClass(e[a])},c=function(){g&&window.clearTimeout(g);d&&d.hide()};return{Show:function(h){if(!h.type)h.type="load";b(h.text,h.type);d.show();g&&window.clearTimeout(g);h.timeout&&(g=window.setTimeout(c,h.timeout))},Hide:function(){c()}}}();
GP.UI=function(){var d=function(b,c,d){var a=b.attr("inpType")=="editor"?b.parents().find("[elEditor='editor']"):b.parent(),i=a.find("[vali_msg='1']");i.length||(i=$('<span class="tip t-err" style="display:none;" vali_msg="1"></span>'),a.append(i));a.find("[vali_msg='0']").hide();c||(c="err");d?i.removeClass(GP.CONFIG.ValiErrorStyle.suc).removeClass(GP.CONFIG.ValiErrorStyle.err).addClass(GP.CONFIG.ValiErrorStyle[c]).html("<i class='ico'></i>"+d).show():i.removeClass(GP.CONFIG.ValiErrorStyle.suc).removeClass(GP.CONFIG.ValiErrorStyle.err).addClass(GP.CONFIG.ValiErrorStyle[c]).html("<i class='ico'></i>"+
b.attr("error")).show()},e=function(){$("[table='1']").each(function(){var b=$(this);b.find("input[type='checkbox'][check='parent']").bind("click",function(){var c=b.find("input[type='checkbox'][check='child']");c.length&&c.attr("checked",$(this).attr("checked"))});b.find("[js_type='delete']").click(function(){var c=$(this);Util.MsgBox.Confirm({text:"\u786e\u8ba4\u8981\u5220\u9664\u5417\uff1f",type:"warm",callback:function(d){if(d){var d=c.attr("href"),a=b.find("input[type='checkbox'][check='child'][checked=true]"),
i=c.attr("js_name");i||(i="id");var f={};a.each(function(a){var d=$(this).val();f[i+"["+a+"]"]=d});$.ajax({url:d,data:f,type:"POST",dataType:"json",success:function(a){a.state==!0?window.location.reload():a.state=="noid"?GP.Message.Show({text:"\u8bf7\u9009\u62e9\u8981\u5220\u9664\u7684\u4fe1\u606f",type:"err",timeout:2E3}):GP.Message.Show({text:"\u5220\u9664\u5931\u8d25",type:"err",timeout:2E3})}})}}});return!1})})},g=function(){$("form[vali]").each(function(){var b=$(this),c=!1;Util.Validate.BindForm(this,
{ErrorCallBack:function(a){b.find("[vali]").each(function(){var a=$(this).attr("inpType")=="editor"?b.find("[elEditor='editor']"):$(this).parent();$(this).attr("ajaxstate")=="-1"||$(this).attr("ajaxstate")=="1"?(a.find("[vali_msg='1']").show(),a.find("[vali_msg='0']").hide()):(a.find("[vali_msg='0']").hide(),a.find("[vali_msg='1']").show())});for(var c in a){var f=$(a[c]);f.attr("ajaxstate")=="-1"||f.attr("ajaxstate")=="1"||d(f)}},ReturnCallBack:function(a,c){var b=a.find("[rate]"),e=$("#"+b.attr("rate"));
e.length&&b.val()!=e.val()&&(d(b),c&&(c=!1));b=a.find("[ajaxstate='-1']");b.length&&(c=!1);if(a.attr("onreturn")){var h=eval(a.attr("onreturn"));h||(c=h)}h&&a.attr("success")&&eval(a.attr("success"));return c}});var e=function(a,b){var f=$(a).attr("type"),a=$(a);if(f=="text"||f=="password"||f=="textarea")for(var e=0,h=b.length;e<h;e++){if(Util.Validate.Check(b[e],a.val())||a.attr("require")=="0"&&$.trim(a.val())=="")c=!1;else{c=!0;break}if(b[e]=="notempty"){var g=a.attr("min")?Number(a.attr("min")):
0,j=a.attr("max")?Number(a.attr("max")):-1,k=$.trim(this.value).length;if(!(g<=k&&(j==-1||j>=k))){c=!0;break}}else c=!1}if(f=="radio"||f=="checkbox")callerName=a.attr("name"),$("input[name='"+callerName+"']:checked").size()==0?c=!0:(c=!1,a.parent().find("[vali_msg='1']").hide(),a.parent().find("[vali_msg='0']").show());f=="select-one"&&(c=a.val()?!1:!0);c?d(a):d(a,"suc"," ");!c&&a.attr("ajax")&&(a.attr("ajaxstate","0"),f={},f[a.attr("name")]=a.val(),$.ajax({url:a.attr("ajax"),type:"POST",data:f,caceh:!1,
success:function(b){$.trim(b)=="success"?(d(a,"suc",a.attr("ajax_suc_msg")),a.attr("ajaxstate","1")):(d(a,"err",b),a.attr("ajaxstate","-1"))}}))};b.find("[vali]").each(function(){var a=$(this),c=a.attr("type"),d=a.attr("vali").split("|");c=="checkbox"?a.bind("click",function(){e(this,d)}):a.bind("blur",function(){e(this,d)}).bind("focus",function(){var c=a.attr("inpType")=="editor"?b.find("[elEditor='editor']"):a.parent();c.find("[vali_msg='1']").hide();c.find("[vali_msg='0']").show()})})})};return{Form:{CreateError:function(b,
c,e){d(b,c,e)},HideError:function(b){b=b.parent().find("[vali_msg='1']");b.length&&b.hide()}},Init:function(){e();g()}}}();
GP.Send=function(){return{SendSubmit:function(){var d=!0,e=$("#msg_body").val().replace("\n","");!Util.Validate.Check("notempty",e)||e.length<1||e.length>1150?(GP.UI.Form.CreateError($("#msg_body"),"err","\u8bf7\u8f93\u51651-1150\u4e2a\u5b57\u7b26\u7684\u5185\u5bb9"),d=!1):(e=$("#msg_body").parent(),e.find("[vali_msg='1']").hide(),e.find("[vali_msg='0']").show());return d},Msg:function(d,e,g){d=String.format('<form id="js_send_msg_box"><table cellspacing="0" cellpadding="0" border="0" class="form" style="margin:10px 0;"><tr><th>\u6536\u4ef6\u4eba\uff1a</th><td><i>%2</i><input type="hidden" value="%1" id="friend_uid" name="to_user_id"></td></tr><tr><th>\u6807\u9898\uff1a</th><td><input type="text" id="msg_subject" name="subject" class="text" /> <span class="gray">\u6807\u9898\u53ef\u4ee5\u4e0d\u9700\u8981\u586b\u5199</span></td></tr><tr><th>\u5185\u5bb9\uff1a</th><td><textarea id="msg_body" name="body"></textarea><span vali_msg="0" class="gray">1150\u5b57\u7b26\u4ee5\u5185</span></td></tr><tr><th>&nbsp;</th><td><button type="submit" class="active">\u7acb\u5373\u53d1\u9001</button>&nbsp;<button type="button" class="bt" onclick="Util.ScreenManager.Hide();">\u53d6\u6d88</button></td></tr></table></form>',
d,e);Util.MsgBox.Show({text:d,title:"\u53d1\u9001\u65b0\u6d88\u606f",width:600});document.getElementById("msg_body").focus();$("#js_send_msg_box").submit(function(){if(GP.Send.SendSubmit()){var b={};$(this).find("[name]").each(function(){b[$(this).attr("name")]=$(this).val()});if(b.subject==""){var c="",c=b.body.length>20?b.body.substring(0,20):b.body.replace("\n","");b.subject=c}$.ajax({url:"?ct=message&ac=ajax_send",type:"POST",data:b,dataType:"json",success:function(b){b.state?(GP.Message.Show({text:"\u53d1\u9001\u6210\u529f",
type:"suc",timeout:2E3}),Util.ScreenManager.Hide()):alert(b.msg)}})}return!1});if(g)document.getElementById("msg_subject").value=g}}}();$(document).ready(function(){GP.UI.Init()});
